[profile.default]
src = "src"
out = "out"
libs = ["lib", "dependencies"]
optimizer_runs = 200


[dependencies]
forge-std = "1.9.6"
"@openzeppelin-contracts" = "5.2.0"
compound-protocol = { version = "2.8.1", git = "https://github.com/compound-finance/compound-protocol.git", rev = "a3214f67b73310d547e00fc578e8355911c9d376" }

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
